name: build ci container

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Install QEMU
      run: |
        sudo apt-get update
        DEBIAN_FRONTEND='noninteractive' sudo apt-get install -qy qemu-user-static buildah
    - uses: actions/checkout@v4
    - name: Build Images
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: rauc-ci-qemu
        tags: latest
        platforms: linux/amd64
        containerfiles: |
          ./Containerfile
    - name: Echo Outputs for Build
      run: |
        echo "Image: ${{ steps.build-image.outputs.image }}"
        echo "Tags: ${{ steps.build-image.outputs.tags }}"
        echo "Tagged Image: ${{ steps.build-image.outputs.image-with-tag }}"
    - name: List Images
      run: |
        buildah images
    - name: Push Images
      id: push-to-github
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/${{ github.repository }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Echo Output for Push
      run: echo "Image pushed to ${{ steps.push-to-github.outputs.registry-paths }}"
